---
kind: Kustomization
resources:
 - performance-namespace.yaml
 - performance-configmap.yaml
 - performance-pvc.yaml
 - performance-secret.yaml
 - performance-rbac.yaml
 - performance-deployment.yaml