---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-pvc
  namespace: testing
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi