apiVersion: locust.io/v1
kind: PlaywrightLocust
metadata:
  namespace: %%NAMESPACE%%
  name: %%LOCUSTTESTNAME%%
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                  - testing
  tolerations:
    - key: workload.sas.com/class
      operator: Equal
      value: testing
      effect: NoSchedule
  image: %%ACRNAME%%/locust-playwright:latest
  imagePullSecrets:
    - name: %%ACR_BASENAME%%pull
  env:
    - name: LOCUST_AUTOSTART
      value: "true"
    - name: TRACE_DIR
      value: /lotest/share/trace
  masterCommandSeed: >
    locust 
    --web-host 0.0.0.0
    --web-port 8089
    --locustfile /lotest/src/%%LOCUSTFILE%%
    --users %%NLOCUSTUSERS%%
    --run-time %%RUNTIME_s%%
    --spawn-rate %%SPAWNRATE_ups%%
    --stop-timeout %%GRACEFUL_EXIT_s%%
    --csv /lotest/share/locust_stats
    --csv-full-history
  workerCommandSeed: >
    locust --worker
    --locustfile /lotest/src/%%LOCUSTFILE%%
  workerReplicas: %%WORKERREPLICAS%%
  configMapRef:
    name: py-pw-loc-configmap
  service:
    name: %%LOCUSTTESTNAME%%-metrics
    port: 8089
    type: ClusterIP
  metrics:
    enabled: true
    exporterImage: rvankruistum/locust-exporter:latest
    port: 9646
  volumes:
    - name: azurefile
      persistentVolumeClaim:
        claimName: azure-file-pvc
  volumeMounts:
    - name: azurefile
      mountPath: /lotest/share
    - name: py-pw-loc-configmap
      mountPath: /lotest/src
  # configMapRef:
  #   name: py-pw-loc-configmap
  initContainers:
    - name: mount-check
      image: busybox
      command: ["sh", "-c", "echo Checking mount && ls /lotest/share"]
      volumeMounts:
        - name: azurefile
          mountPath: /lotest/share
